### ISSUE TITLE
Traceback after player joins game

### ISSUE THREAD

**Issue by matthew-parlette** [matthew-parlette/space-sim#21]
After a player joins the game and a ship is spawned, this traceback shows up on the server:

```
2015-07-06 11:30:45,046:server.py:INFO:join_game(321):Ship 'xxxxx' created
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "game/server.py", line 113, in handle
    state, commands = game.state()
  File "game/server.py", line 21, in state
    return self.game.state()
  File "/home/matt/src/space-sim/game/game.py", line 177, in state
    user_location = self.location(of = self.logged_in_user) if flags['joined_game'] else None
  File "/home/matt/src/space-sim/game/game.py", line 113, in location
    return Game._ships[of.location_id]
KeyError: '274d31ab-1179-453f-8386-458ea2476ce1'
<Greenlet at 0x7f3eded47af0: handle(<socket at 0x7f3eded4d510 fileno=7 sock=192.168.1., ('108.48.124.82', 61170))> failed with KeyError
```

**Comment by matthew-parlette** [comment]
I haven't looked yet, but its likely that the ship isn't being spawned correctly, as this new ship doesn't show up in the `data/ships.yaml` file
