### ISSUE TITLE
Traceback on connection after joining game

### ISSUE THREAD

**Issue by matthew-parlette** [matthew-parlette/space-sim#8]
After the game is created, trying to connect will cause a traceback when loading the shared objects, specifically the sectors:

```
2015-04-10 06:19:04,015:server.py:DEBUG:load_shared_object(92):Loading shared object 'sectors' from data/sectors.yaml...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "game/server.py", line 70, in handle
    game = ServerGameAdapter(log = log, bigbang = args.bigbang)
  File "game/server.py", line 15, in __init__
    self.game = Game(log = log, bigbang = bigbang)
  File "/home/matt/src/space-sim/game/game.py", line 54, in __init__
    self.load_shared_object(obj)
  File "/home/matt/src/space-sim/game/game.py", line 93, in load_shared_object
    loaded_obj = yaml.load(open(filename))
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 129, in construct_mapping
    hash(key)
  File "/home/matt/src/space-sim/game/objects/coordinates.py", line 33, in __hash__
    return hash((self.x, self.y, self.z))
AttributeError: 'Coordinates' object has no attribute 'x'
```

**Comment by matthew-parlette** [comment]
This happens once the game has a player and the server is brought down and started back up.
